### ISSUE TITLE
关于生成的拼图碎片大小

### ISSUE THREAD

**Issue by Maple-214** [MrXujiang/react-slider-vertify#3]
希望能增加个控制大小 的api

**Comment by MrXujiang** [comment]
> 希望能增加个控制大小 的api

已支持，参考：http://h5.dooring.cn/slider-vertify/vertify#%E8%AE%BE%E7%BD%AE%E6%BB%91%E5%9D%97%E8%BE%B9%E9%95%BF%E5%92%8C%E5%8D%8A%E5%BE%84
